dist: xenial
sudo: required

services: 
  - docker
language: go
go:
  - 1.12.6

go_import_path: github.com/alibaba/pouch

before_install:
  |
    echo $TRAVIS_COMMIT_RANGE
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)' || {
      echo "travis does not run for document-only changed"
      exit
    }

install:
  - sudo docker ps -a

notifications:
  webhooks:
    urls:
      - http://47.96.190.121:6789/ci_notifications
    on_failure: always
    on_error: always

jobs:
  include:
    - stage: test
      name: "Unit test"
      arch: amd64
      script: ./travis_ci.sh unittest
    - stage: test
      name: "Unit test"
      arch: arm64
      script: ./travis_ci.sh unittest  

    - stage: test
      name: "CRIv1alpha2 test"
      arch: amd64
      script: ./travis_ci.sh criv1alpha2test
    - stage: test
      name: "CRIv1alpha2 test"
      arch: arm64
      script: ./travis_ci.sh criv1alpha2test  

    - stage: test
      name: "Node e2e test"
      arch: amd64
      script: ./travis_ci.sh nodee2etest
    - stage: test
      name: "Node e2e test"
      arch: arm64
      script: ./travis_ci.sh nodee2etest  

    - stage: test
      name: "Integration test 0"
      arch: amd64
      script: ./travis_ci.sh integrationtest 4 0
    - stage: test
      name: "Integration test 0"
      arch: arm64
      script: ./travis_ci.sh integrationtest 4 0  
    - stage: test
      name: "Integration test 1"
      arch: amd64
      script: ./travis_ci.sh integrationtest 4 1
    - stage: test
      name: "Integration test 1"
      arch: arm64
      script: ./travis_ci.sh integrationtest 4 1  
    - stage: test
      name: "Integration test 2"
      arch: amd64
      script: ./travis_ci.sh integrationtest 4 2
    - stage: test
      name: "Integration test 2"
      arch: arm64
      script: ./travis_ci.sh integrationtest 4 2  
    - stage: test
      name: "Integration test 3"
      arch: amd64
      script: ./travis_ci.sh integrationtest 4 3
    - stage: test
      name: "Integration test 3"
      arch: arm64
      script: ./travis_ci.sh integrationtest 4 3  
